version: '3'
services:
  db: 
    image: postgres
    container_name: ${CONTAINER_DB_NAME}
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - db_data:/var/lib/${DATABASE_NAME}/data

volumes:
  db_data: